<template>
  <div class="dt-root">
    <div class="dt-stats"><div class="dt-stat"><span>派工总数</span><strong>{{ dts.length }}</strong></div><div class="dt-stat"><span>进行中</span><strong class="c-blue">{{ dts.filter(d=>d.status==='RUNNING').length }}</strong></div><div class="dt-stat"><span>已完成</span><strong class="c-green">{{ dts.filter(d=>d.status==='COMPLETED').length }}</strong></div><div class="dt-stat"><span>操作工人数</span><strong>{{ new Set(dts.map(d=>d.operatorId).filter(Boolean)).size }}</strong></div></div>
    <div class="dt-toolbar"><div class="dt-s"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input v-model="kw" placeholder="搜索派工号..." @input="applyF"/></div>
    <select v-model="fs" @change="applyF"><option value="">全部状态</option><option value="CREATED">已创建</option><option value="RUNNING">进行中</option><option value="COMPLETED">已完成</option></select>
    <button class="dt-add" @click="openC">+ 新建派工</button></div>
    <div class="dt-tbl-w"><table class="dt-tbl"><thead><tr><th>派工号</th><th>任务</th><th>工序</th><th>工位</th><th>工人</th><th>计划量</th><th>完成量</th><th>状态</th><th class="th-act">操作</th></tr></thead>
    <tbody><tr v-if="!paged.length"><td colspan="9" class="dt-empty">暂无派工</td></tr>
    <tr v-for="d in paged" :key="d.dispatchId"><td class="mono-s">{{ d.dispatchNo }}</td><td>{{ d.taskNo||'—' }}</td><td>{{ d.stepName||'—' }}</td><td>{{ d.stationName||'—' }}</td><td>{{ d.assigneeName||'—' }}</td><td>{{ d.plannedQty||0 }}</td><td>{{ d.completedQty||0 }}</td>
    <td><span class="st-dot" :class="stC(d.status)"></span>{{ stL(d.status) }}</td>
    <td class="td-act"><button class="ab" @click="openE(d)" title="编辑"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="ab da" @click="openD(d)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
    <div class="dt-pager" v-if="tp>1"><span>共 {{ filtered.length }} 条，{{ pg }} / {{ tp }} 页</span><div class="pg-btns"><button :disabled="pg<=1" @click="pg=1">&laquo;</button><button :disabled="pg<=1" @click="pg--">&lsaquo;</button><button v-for="p in vp" :key="p" :class="{on:p===pg}" @click="pg=p">{{ p }}</button><button :disabled="pg>=tp" @click="pg++">&rsaquo;</button><button :disabled="pg>=tp" @click="pg=tp">&raquo;</button></div></div>

    <Teleport to="body"><div v-if="m.v" class="mod-o" @click.self="closeM"><div class="mod"><div class="mod-h"><h3>{{ m.m==='c'?'新建':'编辑' }}派工</h3><button class="mod-x" @click="closeM">&times;</button></div><div class="mod-b">
      <div class="mr2"><label class="mf"><span>派工号 *</span><input v-model="f.dispatchNo"/></label><label class="mf"><span>任务 *</span><select v-model="f.taskId"><option :value="null">选择</option><option v-for="t in tasks" :key="t.taskId" :value="t.taskId">{{ t.taskNo }}</option></select></label></div>
      <div class="mr2"><label class="mf"><span>工序</span><select v-model="f.stepId"><option :value="null">选择</option><option v-for="s in steps" :key="s.stepId" :value="s.stepId">{{ s.stepName }}</option></select></label><label class="mf"><span>工位</span><select v-model="f.stationId"><option :value="null">选择</option><option v-for="s in stations" :key="s.stationId" :value="s.stationId">{{ s.stationName }}</option></select></label></div>
      <div class="mr2"><label class="mf"><span>工人</span><select v-model="f.assigneeId"><option :value="null">选择</option><option v-for="u in users" :key="u.userId" :value="u.userId">{{ u.realName }}</option></select></label><label class="mf"><span>状态</span><select v-model="f.status"><option value="CREATED">已创建</option><option value="RUNNING">进行中</option><option value="COMPLETED">已完成</option></select></label></div>
    </div><div class="mod-f"><button class="mb s" @click="closeM">取消</button><button class="mb p" @click="submit">{{ m.m==='c'?'创建':'保存' }}</button></div></div></div></Teleport>
    <Teleport to="body"><div v-if="d.v" class="mod-o" @click.self="d.v=false"><div class="dc"><div class="ci-i">!</div><h3>删除派工</h3><p>确定删除 <strong>{{ d.n }}</strong>？</p><div class="ci-a"><button class="mb s" @click="d.v=false">取消</button><button class="mb da" @click="doD">确认删除</button></div></div></div></Teleport>
  </div>
</template>

<script setup>
import { computed,onMounted,reactive,ref } from "vue";import { request } from "@/api/request";
const dts=ref([]),tasks=ref([]),steps=ref([]),stations=ref([]),users=ref([]),kw=ref(""),fs=ref(""),pg=ref(1),ps=10;
const m=reactive({v:false,m:"c"}),d=reactive({v:false,n:"",id:null});const f=reactive({dId:null,dispatchNo:"",taskId:null,stepId:null,stationId:null,assigneeId:null,status:"CREATED"});
onMounted(async()=>{try{dts.value=(await request.get("/planning/dispatch-tasks"))?.data||[]}catch{dts.value=[]};try{tasks.value=(await request.get("/planning/production-tasks"))?.data||[]}catch{tasks.value=[]};try{steps.value=(await request.get("/process/steps"))?.data||[]}catch{steps.value=[]};try{stations.value=(await request.get("/factory/workstations"))?.data||[]}catch{stations.value=[]};try{users.value=(await request.get("/system/users"))?.data||[]}catch{users.value=[]}});
const filtered=computed(()=>{let a=[...dts.value];if(kw.value){const k=kw.value.toLowerCase();a=a.filter(d=>(d.dispatchNo||"").includes(k))}if(fs.value)a=a.filter(d=>d.status===fs.value);return a});
const tp=computed(()=>Math.max(1,Math.ceil(filtered.value.length/ps)));const paged=computed(()=>filtered.value.slice((pg.value-1)*ps,pg.value*ps));const vp=computed(()=>{const t=tp.value,p=pg.value,a=[];let s=Math.max(1,p-2),e=Math.min(t,p+2);for(let i=s;i<=e;i++)a.push(i);return a});function applyF(){pg.value=1}
function stC(s){return s==='RUNNING'?'bl':s==='COMPLETED'?'gr':''}function stL(s){return{ CREATED:'已创建',RUNNING:'进行中',COMPLETED:'已完成'}[s]||s}
function openC(){m.m="c";m.v=true;Object.assign(f,{dId:null,dispatchNo:"",taskId:null,stepId:null,stationId:null,assigneeId:null,status:"CREATED"})}
function openE(dt){m.m="e";m.v=true;Object.assign(f,{dId:dt.dispatchId,dispatchNo:dt.dispatchNo,taskId:null,stepId:dt.stepId,stationId:dt.stationId,assigneeId:dt.operatorId,status:dt.status})}
function closeM(){m.v=false}
async function submit(){const b={dispatchNo:f.dispatchNo,taskId:f.taskId?Number(f.taskId):null,stepId:f.stepId?Number(f.stepId):null,stationId:f.stationId?Number(f.stationId):null,assigneeId:f.assigneeId?Number(f.assigneeId):null,status:f.status};try{if(m.m==="c"){await request.post("/planning/dispatch-tasks",b)}else{await request.put(`/planning/dispatch-tasks/${f.dId}`,b)}closeM();dts.value=(await request.get("/planning/dispatch-tasks"))?.data||[]}catch(e){alert(e?.message)}}
function openD(dt){d.id=dt.dispatchId;d.n=dt.dispatchNo;d.v=true}
async function doD(){try{await request.delete(`/planning/dispatch-tasks/${d.id}`);d.v=false;dts.value=(await request.get("/planning/dispatch-tasks"))?.data||[]}catch(e){alert(e?.message)}}
</script>
<style scoped>
.dt-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}.dt-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.dt-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.dt-stat span{font-size:11px;color:#999}.dt-stat strong{font-size:26px;font-weight:700}.c-blue{color:#2563eb}.c-green{color:#059669}.dt-toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.dt-s{position:relative;flex:1;max-width:300px}.dt-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.dt-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.dt-toolbar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none}.dt-toolbar select option{color:#1a1a1a;background:#fff}.dt-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.dt-add:hover{background:#333}.dt-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.dt-tbl{width:100%;border-collapse:collapse;min-width:800px}.dt-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.dt-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.dt-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.dt-empty{text-align:center;color:#ccc;padding:40px!important}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:6px;background:#bbb}.st-dot.bl{background:#2563eb}.st-dot.gr{background:#059669}.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}.dt-pager{display:flex;align-items:center;justify-content:space-between}.dt-pager span{font-size:12px;color:#999}.pg-btns{display:flex;gap:4px}.pg-btns button{width:30px;height:30px;border:1px solid #e0e0e0;background:#fff;font-size:12px;cursor:pointer;color:#555}.pg-btns button:hover:not(:disabled){background:#f5f5f5}.pg-btns button.on{background:#1a1a1a;color:#fff;border-color:#1a1a1a}.pg-btns button:disabled{opacity:.3;cursor:default}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(540px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}.mb.da{background:#dc2626;color:#fff}.dc{width:400px;background:#fff;border:1px solid #e0e0e0;padding:32px;text-align:center}.ci-i{width:48px;height:48px;border-radius:50%;background:#fef2f2;color:#dc2626;display:inline-grid;place-items:center;font-size:24px;font-weight:700;margin-bottom:12px}.dc h3{margin:0 0 8px;font-size:17px}.dc p{margin:0 0 20px;font-size:14px;color:#777}.ci-a{display:flex;gap:10px;justify-content:center}
</style>
