<template>
  <div class="crud-root">
    <div class="crud-stats"><div class="crud-stat"><span>保养计划</span><strong>{{ plans.length }}</strong></div><div class="crud-stat"><span>点检记录</span><strong>{{ insp.length }}</strong></div></div>
    <div class="crud-tbl-w"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">保养计划</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openPlanC">+ 新建计划</button></div>
    <table class="crud-tbl"><thead><tr><th>编码</th><th>名称</th><th>设备</th><th>频次</th><th>状态</th><th class="th-act">操作</th></tr></thead>
    <tbody><tr v-if="!pPlans.length"><td :colspan="999" class="crud-empty">暂无计划</td></tr><tr v-for="r in pPlans" :key="r.planId"><td class="mono-s">{{ r.planCode }}</td><td>{{ r.planName }}</td><td>{{ r.deviceName||'—' }}</td><td>{{ r.frequencyDesc||'—' }}</td><td><span class="st-dot" :class="r.status==='ENABLED'?'on':''"></span>{{ r.status==='ENABLED'?'启用':'停用' }}</td><td class="td-act"><button class="ab da" @click="doPlanD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
    <div class="crud-tbl-w" style="margin-top:6px"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">点检记录</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openInspC">+ 新建记录</button></div>
    <table class="crud-tbl"><thead><tr><th>编号</th><th>设备</th><th>类型</th><th>结果</th><th>状态</th><th class="th-act">操作</th></tr></thead>
    <tbody><tr v-if="!pInsp.length"><td :colspan="999" class="crud-empty">暂无记录</td></tr><tr v-for="r in pInsp" :key="r.inspectionId"><td class="mono-s">{{ r.inspectionNo }}</td><td>{{ r.deviceName||'—' }}</td><td>{{ r.inspectionType||'—' }}</td><td>{{ r.result||'—' }}</td><td><span class="st-dot" :class="r.status==='ENABLED'?'on':''"></span>{{ r.status==='ENABLED'?'启用':'停用' }}</td><td class="td-act"><button class="ab da" @click="doInspD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
    <Teleport to="body"><div v-if="pm.v" class="mod-o" @click.self="closePlanM"><div class="mod"><div class="mod-h"><h3>新建保养计划</h3><button class="mod-x" @click="closePlanM">&times;</button></div><div class="mod-b"><div class="mr2"><label class="mf"><span>编码</span><input v-model="pff.planCode"/></label><label class="mf"><span>名称</span><input v-model="pff.planName"/></label></div><label class="mf"><span>设备</span><select v-model="pff.deviceId"><option :value="null">请选择</option><option v-for="d in devices" :key="d.deviceId" :value="d.deviceId">{{d.deviceName}}</option></select></label><div class="mr2"><label class="mf"><span>频次</span><input v-model="pff.frequencyDesc"/></label><label class="mf"><span>状态</span><select v-model="pff.status"><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label></div></div><div class="mod-f"><button class="mb s" @click="closePlanM">取消</button><button class="mb p" @click="submitPlan">创建</button></div></div></div></Teleport>
    <Teleport to="body"><div v-if="im.v" class="mod-o" @click.self="closeInspM"><div class="mod"><div class="mod-h"><h3>新建点检记录</h3><button class="mod-x" @click="closeInspM">&times;</button></div><div class="mod-b"><div class="mr2"><label class="mf"><span>编号</span><input v-model="iff.inspectionNo"/></label><label class="mf"><span>设备</span><select v-model="iff.deviceId"><option :value="null">请选择</option><option v-for="d in devices" :key="d.deviceId" :value="d.deviceId">{{d.deviceName}}</option></select></label></div><div class="mr2"><label class="mf"><span>类型</span><input v-model="iff.inspectionType"/></label><label class="mf"><span>结果</span><input v-model="iff.result"/></label></div><label class="mf"><span>状态</span><select v-model="iff.status"><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label></div><div class="mod-f"><button class="mb s" @click="closeInspM">取消</button><button class="mb p" @click="submitInsp">创建</button></div></div></div></Teleport></div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from "vue";import {request} from "@/api/request";
const plans=ref([]),insp=ref([]),devices=ref([]),planPg=ref(1),inspPg=ref(1),ps=10;
const pff=reactive({planCode:"",planName:"",deviceId:null,frequencyDesc:"",status:"ENABLED"});
const iff=reactive({inspectionNo:"",deviceId:null,inspectionType:"",result:"",status:"ENABLED"});
const pm=reactive({v:false});const im=reactive({v:false});
const pPlans=computed(()=>plans.value.slice((planPg.value-1)*ps,planPg.value*ps));
const pInsp=computed(()=>insp.value.slice((inspPg.value-1)*ps,inspPg.value*ps));
const planTp=computed(()=>Math.ceil(plans.value.length/ps)||1);
const inspTp=computed(()=>Math.ceil(insp.value.length/ps)||1);
async function ld(){try{plans.value=(await request.get("/equipment/maintenance-plans"))?.data||[]}catch{plans.value=[]};try{insp.value=(await request.get("/equipment/inspections"))?.data||[]}catch{insp.value=[]};try{devices.value=(await request.get("/equipment/devices"))?.data||[]}catch{}}
function openPlanC(){Object.assign(pff,{planCode:"",planName:"",deviceId:null,frequencyDesc:"",status:"ENABLED"});pm.v=true}
function closePlanM(){pm.v=false}
async function submitPlan(){try{await request.post("/equipment/maintenance-plans",{...pff,deviceId:pff.deviceId?Number(pff.deviceId):null});pm.v=false;await ld()}catch(e){alert(e?.message)}}
async function doPlanD(r){if(confirm(`删除 ${r.planName}?`)){try{await request.delete(`/equipment/maintenance-plans/${r.planId}`);await ld()}catch(e){alert(e?.message)}}}
function openInspC(){Object.assign(iff,{inspectionNo:"",deviceId:null,inspectionType:"",result:"",status:"ENABLED"});im.v=true}
function closeInspM(){im.v=false}
async function submitInsp(){try{await request.post("/equipment/inspections",{...iff,deviceId:iff.deviceId?Number(iff.deviceId):null});im.v=false;await ld()}catch(e){alert(e?.message)}}
async function doInspD(r){if(confirm("删除此记录？")){try{await request.delete(`/equipment/inspections/${r.inspectionId}`);await ld()}catch(e){alert(e?.message)}}}
onMounted(ld)
</script>
<style scoped>
.crud-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}
.crud-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.crud-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.crud-stat span{font-size:11px;color:#999}.crud-stat strong{font-size:26px;font-weight:700}.c-green{color:#059669}.c-blue{color:#2563eb}.c-red{color:#dc2626}
.crud-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.crud-s{position:relative;flex:1;max-width:300px}.crud-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.crud-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.crud-bar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none;min-width:80px}.crud-bar select option{color:#1a1a1a;background:#fff}.crud-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.crud-add:hover{background:#333}
.crud-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.crud-tbl{width:100%;border-collapse:collapse}.crud-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.crud-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.crud-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.crud-empty{text-align:center;color:#ccc;padding:40px!important}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:6px;background:#bbb}.st-dot.on{background:#059669}
.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}
.crud-pager{display:flex;align-items:center;justify-content:space-between}.crud-pager span{font-size:12px;color:#999}.pg-btns{display:flex;gap:4px}.pg-btns button{width:30px;height:30px;border:1px solid #e0e0e0;background:#fff;font-size:12px;cursor:pointer;color:#555}.pg-btns button:hover:not(:disabled){background:#f5f5f5}.pg-btns button.on{background:#1a1a1a;color:#fff;border-color:#1a1a1a}.pg-btns button:disabled{opacity:.3;cursor:default}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(520px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}
</style>
