<template>
  <div class="crud-root"><div class="crud-stats"><div class="crud-stat"><span>总数</span><strong>{{ list.length }}</strong></div><div class="crud-stat"><span>启用</span><strong class="c-green">{{ list.filter(x=>x.status==='ENABLED'||x.status==='ACTIVE').length }}</strong></div></div>
  <div class="crud-bar"><div class="crud-s"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input v-model="kw" placeholder="搜索..." @input="applyF"/></div><select v-model="fs" @change="applyF"><option value="">全部</option><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select><button class="crud-add" @click="openC">+ 新建工艺路线</button></div>
  <div class="crud-tbl-w"><table class="crud-tbl"><thead><tr><th>编码</th><th>名称</th><th>版本</th><th>状态</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!paged.length"><td :colspan="999" class="crud-empty">暂无数据</td></tr><tr v-for="r in paged" :key="r.routeId" @click="toggleSteps(r.routeId)" style="cursor:pointer"><td class="mono-s">{{ r.routeCode }}</td><td>{{ r.routeName }}</td><td>{{ r.versionNo||'—' }}</td><td><span class="st-dot" :class="r.status==='ENABLED'?'on':''"></span>{{ r.status==='ENABLED'?'启用':'停用' }}</td><td class="td-act"><button class="ab" @click.stop="openE(r)" title="编辑"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="ab da" @click.stop="doD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <div class="crud-pager" v-if="tp>1"><span>{{ pg }}/{{ tp }} 页</span><div class="pg-btns"><button :disabled="pg<=1" @click="pg=1">&laquo;</button><button :disabled="pg<=1" @click="pg--">&lsaquo;</button><button v-for="p in vp" :key="p" :class="{on:p===pg}" @click="pg=p">{{ p }}</button><button :disabled="pg>=tp" @click="pg++">&rsaquo;</button><button :disabled="pg>=tp" @click="pg=tp">&raquo;</button></div></div>
  <div v-if="selRoute" class="crud-tbl-w" style="margin-top:14px"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">工艺步骤 — {{selRoute.routeName}}</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openStepM">+ 添加步骤</button></div>
  <table class="crud-tbl"><thead><tr><th>序号</th><th>步骤名称</th><th>步骤编码</th><th>工位</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!steps.length"><td :colspan="999" class="crud-empty">暂无步骤</td></tr><tr v-for="s in steps" :key="s.routeStepId"><td>{{ s.stepSeq }}</td><td>{{ s.stepName }}</td><td class="mono-s">{{ s.stepCode }}</td><td>{{ s.stationName||'—' }}</td><td class="td-act"><button class="ab da" @click="delStep(s)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <Teleport to="body"><div v-if="m.v" class="mod-o" @click.self="closeM"><div class="mod"><div class="mod-h"><h3>{{ m.m==='c'?'新建':'编辑' }}工艺路线</h3><button class="mod-x" @click="closeM">&times;</button></div><div class="mod-b"><div class="mr2"><label class="mf"><span>编码</span><input v-model="ff.routeCode"/></label><label class="mf"><span>名称</span><input v-model="ff.routeName"/></label></div><div class="mr2"><label class="mf"><span>版本</span><input v-model="ff.versionNo"/></label><label class="mf"><span>状态</span><select v-model="ff.status"><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label></div></div><div class="mod-f"><button class="mb s" @click="closeM">取消</button><button class="mb p" @click="submit">{{ m.m==='c'?'创建':'保存' }}</button></div></div></div></Teleport>
  <Teleport to="body"><div v-if="sm.v" class="mod-o" @click.self="closeStepM"><div class="mod"><div class="mod-h"><h3>添加工艺步骤</h3><button class="mod-x" @click="closeStepM">&times;</button></div><div class="mod-b"><div class="mr2"><label class="mf"><span>序号</span><input v-model="sff.stepSeq"/></label><label class="mf"><span>步骤名称</span><input v-model="sff.stepName"/></label></div><div class="mr2"><label class="mf"><span>步骤编码</span><input v-model="sff.stepCode"/></label><label class="mf"><span>工位</span><select v-model="sff.stationId"><option :value="null">请选择</option><option v-for="s in stations" :key="s.stationId" :value="s.stationId">{{s.stationName}}</option></select></label></div></div><div class="mod-f"><button class="mb s" @click="closeStepM">取消</button><button class="mb p" @click="submitStep">添加</button></div></div></div></Teleport></div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from "vue";import {request} from "@/api/request";
const list=ref([]),steps=ref([]),stations=ref([]),selRoute=ref(null),kw=ref(""),fs=ref(""),pg=ref(1),ps=10;
const ff=reactive({routeCode:"",routeName:"",versionNo:"V1.0",status:"ENABLED"});
const sff=reactive({stepSeq:"1",stepName:"",stepCode:"",stationId:null});
const m=reactive({v:false,m:"c",id:null});const sm=reactive({v:false});
const fl=computed(()=>{let a=list.value;if(kw.value)a=a.filter(x=>(x.routeName||"").includes(kw.value)||(x.routeCode||"").includes(kw.value));if(fs.value)a=a.filter(x=>x.status===fs.value);return a});
const tp=computed(()=>Math.ceil(fl.value.length/ps)||1);
const vp=computed(()=>{let s=Math.max(1,pg.value-2),e=Math.min(tp.value,s+4);s=Math.max(1,e-4);let r=[];for(let i=s;i<=e;i++)r.push(i);return r});
const paged=computed(()=>fl.value.slice((pg.value-1)*ps,pg.value*ps));
function applyF(){pg.value=1}
async function ld(){try{list.value=(await request.get("/process/routes"))?.data||[];stations.value=(await request.get("/factory/workstations"))?.data||[]}catch{list.value=[]}}
async function loadSteps(){if(selRoute.value){try{steps.value=(await request.get(`/process/routes/${selRoute.value.routeId}/steps`))?.data||[]}catch{steps.value=[]}}}
function toggleSteps(routeId){const r=list.value.find(x=>x.routeId===routeId);selRoute.value=selRoute.value?.routeId===routeId?null:r;if(selRoute.value)loadSteps();else steps.value=[]}
function openC(){Object.assign(ff,{routeCode:"",routeName:"",versionNo:"V1.0",status:"ENABLED"});m.v=true;m.m="c";m.id=null}
function openE(r){Object.assign(ff,{routeCode:r.routeCode,routeName:r.routeName,versionNo:r.versionNo||"V1.0",status:r.status});m.v=true;m.m="e";m.id=r.routeId}
function closeM(){m.v=false}
async function submit(){const p={routeCode:ff.routeCode,routeName:ff.routeName,versionNo:ff.versionNo,status:ff.status};try{if(m.m==="c"){await request.post("/process/routes",p)}else{await request.put(`/process/routes/${m.id}`,p)}m.v=false;await ld()}catch(e){alert(e?.message)}}
async function doD(r){if(confirm(`删除 ${r.routeName}?`)){try{await request.delete(`/process/routes/${r.routeId}`);if(selRoute.value?.routeId===r.routeId){selRoute.value=null;steps.value=[]}await ld()}catch(e){alert(e?.message)}}}
function openStepM(){Object.assign(sff,{stepSeq:String(steps.length+1),stepName:"",stepCode:"",stationId:null});sm.v=true}
function closeStepM(){sm.v=false}
async function submitStep(){try{await request.post(`/process/routes/${selRoute.value.routeId}/steps`,{routeId:selRoute.value.routeId,stepSeq:Number(sff.stepSeq),stepName:sff.stepName,stepCode:sff.stepCode,stationId:sff.stationId?Number(sff.stationId):null});sm.v=false;await loadSteps()}catch(e){alert(e?.message)}}
async function delStep(s){if(confirm("移除此步骤？")){try{await request.delete(`/process/routes/${selRoute.value.routeId}/steps/${s.routeStepId}`);await loadSteps()}catch(e){alert(e?.message)}}}
onMounted(ld)
</script>
<style scoped>
.crud-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}
.crud-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.crud-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.crud-stat span{font-size:11px;color:#999}.crud-stat strong{font-size:26px;font-weight:700}.c-green{color:#059669}.c-blue{color:#2563eb}.c-red{color:#dc2626}
.crud-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.crud-s{position:relative;flex:1;max-width:300px}.crud-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.crud-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.crud-bar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none;min-width:80px}.crud-bar select option{color:#1a1a1a;background:#fff}.crud-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.crud-add:hover{background:#333}
.crud-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.crud-tbl{width:100%;border-collapse:collapse}.crud-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.crud-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.crud-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.crud-empty{text-align:center;color:#ccc;padding:40px!important}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:6px;background:#bbb}.st-dot.on{background:#059669}
.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}
.crud-pager{display:flex;align-items:center;justify-content:space-between}.crud-pager span{font-size:12px;color:#999}.pg-btns{display:flex;gap:4px}.pg-btns button{width:30px;height:30px;border:1px solid #e0e0e0;background:#fff;font-size:12px;cursor:pointer;color:#555}.pg-btns button:hover:not(:disabled){background:#f5f5f5}.pg-btns button.on{background:#1a1a1a;color:#fff;border-color:#1a1a1a}.pg-btns button:disabled{opacity:.3;cursor:default}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(520px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}
</style>
