<template>
  <div class="crud-root"><div class="crud-stats"><div class="crud-stat"><span>检验记录</span><strong>{{ records.length }}</strong></div><div class="crud-stat"><span>质量放行</span><strong>{{ releases.length }}</strong></div></div>
  <div class="crud-tbl-w"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">检验记录</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openRecordM">+ 新增</button></div>
  <table class="crud-tbl"><thead><tr><th>记录编号</th><th>任务编号</th><th>检验类型</th><th>结果</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!pRecords.length"><td :colspan="999" class="crud-empty">暂无记录</td></tr><tr v-for="r in pRecords" :key="r.qualityRecordId"><td class="mono-s">{{ r.qualityRecordNo }}</td><td>{{ r.qualityTaskNo||'—' }}</td><td>{{ r.inspectType||'—' }}</td><td><span :class="r.inspectResult==='PASS'?'c-green':r.inspectResult==='FAIL'?'c-red':'c-blue'" style="font-weight:600">{{ r.inspectResult||'—' }}</span></td><td class="td-act"><button class="ab da" @click="doRecD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <div class="crud-tbl-w" style="margin-top:6px"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">质量放行</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openRelM">+ 新增</button></div>
  <table class="crud-tbl"><thead><tr><th>放行编号</th><th>关联记录</th><th>结果</th><th>状态</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!pReleases.length"><td :colspan="999" class="crud-empty">暂无记录</td></tr><tr v-for="r in pReleases" :key="r.releaseId"><td class="mono-s">{{ r.releaseNo }}</td><td>{{ r.qualityRecordNo||'—' }}</td><td><span :class="r.releaseResult==='RELEASE'?'c-green':r.releaseResult==='BLOCK'?'c-red':'c-blue'" style="font-weight:600">{{ r.releaseResult||'—' }}</span></td><td>{{ r.status||'—' }}</td><td class="td-act"><button class="ab da" @click="doRelD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <Teleport to="body"><div v-if="rm.v" class="mod-o" @click.self="closeRecM"><div class="mod"><div class="mod-h"><h3>新增检验记录</h3><button class="mod-x" @click="closeRecM">&times;</button></div><div class="mod-b"><label class="mf"><span>记录编号</span><input v-model="rff.qualityRecordNo"/></label><label class="mf"><span>任务编号</span><input v-model="rff.qualityTaskNo"/></label><label class="mf"><span>检验类型</span><input v-model="rff.inspectType"/></label><label class="mf"><span>检验结果</span><select v-model="rff.inspectResult"><option value="PASS">PASS</option><option value="FAIL">FAIL</option><option value="CONCESSION">CONCESSION</option></select></label></div><div class="mod-f"><button class="mb s" @click="closeRecM">取消</button><button class="mb p" @click="submitRec">保存</button></div></div></div></Teleport>
  <Teleport to="body"><div v-if="lm.v" class="mod-o" @click.self="closeRelM"><div class="mod"><div class="mod-h"><h3>新增质量放行</h3><button class="mod-x" @click="closeRelM">&times;</button></div><div class="mod-b"><label class="mf"><span>放行编号</span><input v-model="lff.releaseNo"/></label><label class="mf"><span>关联记录ID</span><input v-model="lff.qualityRecordId"/></label><label class="mf"><span>放行结果</span><select v-model="lff.releaseResult"><option value="RELEASE">RELEASE</option><option value="BLOCK">BLOCK</option><option value="CONCESSION">CONCESSION</option></select></label><label class="mf"><span>状态</span><select v-model="lff.status"><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label></div><div class="mod-f"><button class="mb s" @click="closeRelM">取消</button><button class="mb p" @click="submitRel">保存</button></div></div></div></Teleport></div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from "vue";import {request} from "@/api/request";
const records=ref([]),releases=ref([]),recPg=ref(1),relPg=ref(1),ps=10;
const rff=reactive({qualityRecordNo:"",qualityTaskNo:"",inspectType:"",inspectResult:"PASS"});
const lff=reactive({releaseNo:"",qualityRecordId:"",releaseResult:"RELEASE",status:"ENABLED"});
const rm=reactive({v:false});const lm=reactive({v:false});
const pRecords=computed(()=>records.value.slice((recPg.value-1)*ps,recPg.value*ps));
const pReleases=computed(()=>releases.value.slice((relPg.value-1)*ps,relPg.value*ps));
async function ld(){try{records.value=(await request.get("/quality/records"))?.data||[]}catch{records.value=[]};try{releases.value=(await request.get("/quality/releases"))?.data||[]}catch{releases.value=[]}}
function openRecordM(){Object.assign(rff,{qualityRecordNo:"",qualityTaskNo:"",inspectType:"",inspectResult:"PASS"});rm.v=true}
function closeRecM(){rm.v=false}
async function submitRec(){try{await request.post("/quality/records",{qualityRecordNo:rff.qualityRecordNo,qualityTaskNo:rff.qualityTaskNo,inspectType:rff.inspectType,inspectResult:rff.inspectResult});rm.v=false;await ld()}catch(e){alert(e?.message)}}
async function doRecD(r){if(confirm("删除？")){try{await request.delete(`/quality/records/${r.qualityRecordId}`);await ld()}catch(e){alert(e?.message)}}}
function openRelM(){Object.assign(lff,{releaseNo:"",qualityRecordId:"",releaseResult:"RELEASE",status:"ENABLED"});lm.v=true}
function closeRelM(){lm.v=false}
async function submitRel(){try{await request.post("/quality/releases",{releaseNo:lff.releaseNo,qualityRecordId:lff.qualityRecordId?Number(lff.qualityRecordId):null,releaseResult:lff.releaseResult,status:lff.status});lm.v=false;await ld()}catch(e){alert(e?.message)}}
async function doRelD(r){if(confirm("删除？")){try{await request.delete(`/quality/releases/${r.releaseId}`);await ld()}catch(e){alert(e?.message)}}}
onMounted(ld)
</script>
<style scoped>
.crud-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}
.crud-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.crud-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.crud-stat span{font-size:11px;color:#999}.crud-stat strong{font-size:26px;font-weight:700}.c-green{color:#059669}.c-blue{color:#2563eb}.c-red{color:#dc2626}
.crud-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.crud-s{position:relative;flex:1;max-width:300px}.crud-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.crud-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.crud-bar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none;min-width:80px}.crud-bar select option{color:#1a1a1a;background:#fff}.crud-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.crud-add:hover{background:#333}
.crud-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.crud-tbl{width:100%;border-collapse:collapse}.crud-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.crud-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.crud-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.crud-empty{text-align:center;color:#ccc;padding:40px!important}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:6px;background:#bbb}.st-dot.on{background:#059669}
.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(520px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}
</style>
