<template>
  <div class="crud-root"><div class="crud-stats"><div class="crud-stat"><span>总数</span><strong>{{ list.length }}</strong></div><div class="crud-stat"><span>已批准</span><strong class="c-green">{{ list.filter(x=>x.status==='APPROVED').length }}</strong></div></div>
  <div class="crud-bar"><div class="crud-s"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input v-model="kw" placeholder="搜索..." @input="applyF"/></div><button class="crud-add" @click="openC">+ 新建领料单</button></div>
  <div class="crud-tbl-w"><table class="crud-tbl"><thead><tr><th>单号</th><th>工单</th><th>申请人</th><th>状态</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!paged.length"><td :colspan="999" class="crud-empty">暂无数据</td></tr><tr v-for="r in paged" :key="r.requisitionId" @click="toggleItems(r.requisitionId)" style="cursor:pointer"><td class="mono-s">{{ r.requisitionNo }}</td><td>{{ r.workOrderNo||'—' }}</td><td>{{ r.requestUserName||'—' }}</td><td>{{ r.status==='CREATED'?'已创建':r.status==='APPROVED'?'已批准':r.status==='ISSUED'?'已发料':r.status||'—' }}</td><td class="td-act"><button class="ab" @click.stop="openE(r)" title="编辑"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="ab da" @click.stop="doD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <div class="crud-pager" v-if="tp>1"><span>{{ pg }}/{{ tp }} 页</span><div class="pg-btns"><button :disabled="pg<=1" @click="pg=1">&laquo;</button><button :disabled="pg<=1" @click="pg--">&lsaquo;</button><button v-for="p in vp" :key="p" :class="{on:p===pg}" @click="pg=p">{{ p }}</button><button :disabled="pg>=tp" @click="pg++">&rsaquo;</button><button :disabled="pg>=tp" @click="pg=tp">&raquo;</button></div></div>
  <div v-if="selReq" class="crud-tbl-w" style="margin-top:14px"><div style="padding:12px 14px;border-bottom:1px solid #eee;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:14px">领料明细 — {{selReq.requisitionNo}}</strong><button class="crud-add" style="height:28px;font-size:12px;padding:0 10px" @click="openItemM">+ 添加物料</button></div>
  <table class="crud-tbl"><thead><tr><th>物料编码</th><th>物料名称</th><th>申请数量</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!items.length"><td :colspan="999" class="crud-empty">暂无明细</td></tr><tr v-for="it in items" :key="it.requisitionItemId"><td class="mono-s">{{ it.materialCode }}</td><td>{{ it.materialName }}</td><td>{{ it.requestQty }}</td><td class="td-act"><button class="ab da" @click="delItem(it)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <Teleport to="body"><div v-if="m.v" class="mod-o" @click.self="closeM"><div class="mod"><div class="mod-h"><h3>{{ m.m==='c'?'新建':'编辑' }}领料单</h3><button class="mod-x" @click="closeM">&times;</button></div><div class="mod-b"><label class="mf"><span>领料单号</span><input v-model="ff.requisitionNo"/></label><label class="mf"><span>工单</span><select v-model="ff.workOrderId"><option :value="null">请选择</option><option v-for="w in wos" :key="w.workOrderId" :value="w.workOrderId">{{w.workOrderNo}}</option></select></label><label class="mf"><span>申请人</span><select v-model="ff.requestUserId"><option :value="null">请选择</option><option v-for="u in users" :key="u.userId" :value="u.userId">{{u.realName}}</option></select></label><label class="mf"><span>状态</span><select v-model="ff.status"><option value="CREATED">已创建</option><option value="APPROVED">已批准</option><option value="ISSUED">已发料</option></select></label></div><div class="mod-f"><button class="mb s" @click="closeM">取消</button><button class="mb p" @click="submit">{{ m.m==='c'?'创建':'保存' }}</button></div></div></div></Teleport>
  <Teleport to="body"><div v-if="im.v" class="mod-o" @click.self="closeItemM"><div class="mod"><div class="mod-h"><h3>添加物料</h3><button class="mod-x" @click="closeItemM">&times;</button></div><div class="mod-b"><label class="mf"><span>物料</span><select v-model="ifm.materialId"><option :value="null">请选择</option><option v-for="m in materials" :key="m.materialId" :value="m.materialId">{{m.materialCode}} - {{m.materialName}}</option></select></label><label class="mf"><span>申请数量</span><input v-model="ifm.requestQty"/></label></div><div class="mod-f"><button class="mb s" @click="closeItemM">取消</button><button class="mb p" @click="submitItem">添加</button></div></div></div></Teleport></div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from "vue";import {request} from "@/api/request";
const list=ref([]),items=ref([]),wos=ref([]),users=ref([]),materials=ref([]),selReq=ref(null),kw=ref(""),pg=ref(1),ps=10;
const ff=reactive({requisitionNo:"",workOrderId:null,requestUserId:null,status:"CREATED"});
const ifm=reactive({materialId:null,requestQty:"1"});
const m=reactive({v:false,m:"c",id:null});const im=reactive({v:false});
const fl=computed(()=>{let a=list.value;if(kw.value)a=a.filter(x=>(x.requisitionNo||"").includes(kw.value));return a});
const tp=computed(()=>Math.ceil(fl.value.length/ps)||1);
const vp=computed(()=>{let s=Math.max(1,pg.value-2),e=Math.min(tp.value,s+4);s=Math.max(1,e-4);let r=[];for(let i=s;i<=e;i++)r.push(i);return r});
const paged=computed(()=>fl.value.slice((pg.value-1)*ps,pg.value*ps));
function applyF(){pg.value=1}
async function ld(){try{list.value=(await request.get("/inventory/requisitions"))?.data||[];wos.value=(await request.get("/planning/work-orders"))?.data||[];users.value=(await request.get("/system/users"))?.data||[];materials.value=(await request.get("/master-data/materials"))?.data||[]}catch{list.value=[]}}
async function loadItems(){if(selReq.value){try{items.value=(await request.get(`/inventory/requisitions/${selReq.value}/items`))?.data||[]}catch{items.value=[]}}}
function toggleItems(id){const r=list.value.find(x=>x.requisitionId===id);selReq.value=selReq.value?.requisitionId===id?null:r;if(selReq.value)loadItems();else items.value=[]}
function openC(){Object.assign(ff,{requisitionNo:"",workOrderId:null,requestUserId:null,status:"CREATED"});m.v=true;m.m="c";m.id=null}
function openE(r){Object.assign(ff,{requisitionNo:r.requisitionNo,workOrderId:r.workOrderId||null,requestUserId:r.requestUserId||null,status:r.status||"CREATED"});m.v=true;m.m="e";m.id=r.requisitionId}
function closeM(){m.v=false}
async function submit(){const p={requisitionNo:ff.requisitionNo,workOrderId:ff.workOrderId?Number(ff.workOrderId):null,requestUserId:ff.requestUserId?Number(ff.requestUserId):null,status:ff.status};try{if(m.m==="c"){await request.post("/inventory/requisitions",p)}else{await request.put(`/inventory/requisitions/${m.id}`,p)}m.v=false;await ld()}catch(e){alert(e?.message)}}
async function doD(r){if(confirm(`删除 ${r.requisitionNo}?`)){try{await request.delete(`/inventory/requisitions/${r.requisitionId}`);if(selReq.value?.requisitionId===r.requisitionId){selReq.value=null;items.value=[]}await ld()}catch(e){alert(e?.message)}}}
function openItemM(){Object.assign(ifm,{materialId:null,requestQty:"1"});im.v=true}
function closeItemM(){im.v=false}
async function submitItem(){try{await request.post(`/inventory/requisitions/${selReq.value.requisitionId}/items`,{materialId:Number(ifm.materialId),requestQty:Number(ifm.requestQty)});im.v=false;await loadItems()}catch(e){alert(e?.message)}}
async function delItem(it){if(confirm("移除此物料？")){try{await request.delete(`/inventory/requisitions/${selReq.value.requisitionId}/items/${it.requisitionItemId}`);await loadItems()}catch(e){alert(e?.message)}}}
onMounted(ld)
</script>
<style scoped>
.crud-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}
.crud-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.crud-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.crud-stat span{font-size:11px;color:#999}.crud-stat strong{font-size:26px;font-weight:700}.c-green{color:#059669}.c-blue{color:#2563eb}.c-red{color:#dc2626}
.crud-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.crud-s{position:relative;flex:1;max-width:300px}.crud-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.crud-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.crud-bar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none;min-width:80px}.crud-bar select option{color:#1a1a1a;background:#fff}.crud-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.crud-add:hover{background:#333}
.crud-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.crud-tbl{width:100%;border-collapse:collapse}.crud-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.crud-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.crud-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.crud-empty{text-align:center;color:#ccc;padding:40px!important}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:6px;background:#bbb}.st-dot.on{background:#059669}
.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}
.crud-pager{display:flex;align-items:center;justify-content:space-between}.crud-pager span{font-size:12px;color:#999}.pg-btns{display:flex;gap:4px}.pg-btns button{width:30px;height:30px;border:1px solid #e0e0e0;background:#fff;font-size:12px;cursor:pointer;color:#555}.pg-btns button:hover:not(:disabled){background:#f5f5f5}.pg-btns button.on{background:#1a1a1a;color:#fff;border-color:#1a1a1a}.pg-btns button:disabled{opacity:.3;cursor:default}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(520px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}
</style>
