<template>
  <div class="crud-root"><div class="crud-stats"><div class="crud-stat"><span>仓库总数</span><strong>{{ list.length }}</strong></div><div class="crud-stat"><span>启用</span><strong class="c-green">{{ list.filter(x=>x.status==='ENABLED').length }}</strong></div></div>
  <div class="wd-grid"><div v-for="w in list" :key="w.warehouseId" class="wd-card"><div class="wd-card-head"><strong>{{ w.warehouseName }}</strong><span class="mono-s">{{ w.warehouseCode }}</span><span class="st-dot" :class="w.status==='ENABLED'?'on':''"></span></div><div class="wd-card-body"><div class="wd-stat"><span>批次</span><strong>{{ batchCounts[w.warehouseId]||0 }}</strong></div><div class="wd-stat"><span>总库存</span><strong>{{ batchQtys[w.warehouseId]||0 }}</strong></div></div></div></div>
  <div class="crud-bar" style="margin-top:6px"><button class="crud-add" @click="openC">+ 新建仓库</button></div>
  <div class="crud-tbl-w"><table class="crud-tbl"><thead><tr><th>编码</th><th>名称</th><th>状态</th><th class="th-act">操作</th></tr></thead>
  <tbody><tr v-if="!list.length"><td :colspan="999" class="crud-empty">暂无数据</td></tr><tr v-for="r in list" :key="r.warehouseId"><td class="mono-s">{{ r.warehouseCode }}</td><td>{{ r.warehouseName }}</td><td><span class="st-dot" :class="r.status==='ENABLED'?'on':''"></span>{{ r.status==='ENABLED'?'启用':'停用' }}</td><td class="td-act"><button class="ab" @click="openE(r)" title="编辑"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="ab da" @click="doD(r)" title="删除"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr></tbody></table></div>
  <Teleport to="body"><div v-if="m.v" class="mod-o" @click.self="closeM"><div class="mod"><div class="mod-h"><h3>{{ m.m==='c'?'新建':'编辑' }}仓库</h3><button class="mod-x" @click="closeM">&times;</button></div><div class="mod-b"><div class="mr2"><label class="mf"><span>编码</span><input v-model="ff.warehouseCode"/></label><label class="mf"><span>名称</span><input v-model="ff.warehouseName"/></label></div><label class="mf"><span>状态</span><select v-model="ff.status"><option value="ENABLED">启用</option><option value="DISABLED">停用</option></select></label></div><div class="mod-f"><button class="mb s" @click="closeM">取消</button><button class="mb p" @click="submit">{{ m.m==='c'?'创建':'保存' }}</button></div></div></div></Teleport></div>
</template>
<script setup>
import {onMounted,reactive,ref} from "vue";import {request} from "@/api/request";
const list=ref([]),batchCounts=reactive({}),batchQtys=reactive({});
const ff=reactive({warehouseCode:"",warehouseName:"",status:"ENABLED"});
const m=reactive({v:false,m:"c",id:null});
async function ld(){try{list.value=(await request.get("/inventory/warehouses"))?.data||[];for(const w of list.value){try{const b=(await request.get("/inventory/batches"))?.data||[];const fb=b.filter(x=>x.warehouseId===w.warehouseId);batchCounts[w.warehouseId]=fb.length;batchQtys[w.warehouseId]=fb.reduce((s,x)=>s+(Number(x.availableQty)||0),0)}catch{batchCounts[w.warehouseId]=0;batchQtys[w.warehouseId]=0}}}catch{list.value=[]}}
function openC(){Object.assign(ff,{warehouseCode:"",warehouseName:"",status:"ENABLED"});m.v=true;m.m="c";m.id=null}
function openE(r){Object.assign(ff,{warehouseCode:r.warehouseCode,warehouseName:r.warehouseName,status:r.status});m.v=true;m.m="e";m.id=r.warehouseId}
function closeM(){m.v=false}
async function submit(){const p={warehouseCode:ff.warehouseCode,warehouseName:ff.warehouseName,status:ff.status};try{if(m.m==="c"){await request.post("/inventory/warehouses",p)}else{await request.put(`/inventory/warehouses/${m.id}`,p)}m.v=false;await ld()}catch(e){alert(e?.message)}}
async function doD(r){if(confirm(`删除 ${r.warehouseName}?`)){try{await request.delete(`/inventory/warehouses/${r.warehouseId}`);await ld()}catch(e){alert(e?.message)}}}
onMounted(ld)
</script>
<style scoped>
.crud-root{display:grid;gap:14px}.mono-s{font-family:"JetBrains Mono",monospace;font-size:12px;color:#999}
.crud-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.crud-stat{background:#fff;border:1px solid #e0e0e0;padding:14px 18px;display:flex;flex-direction:column;gap:4px}.crud-stat span{font-size:11px;color:#999}.crud-stat strong{font-size:26px;font-weight:700}.c-green{color:#059669}.c-blue{color:#2563eb}.c-red{color:#dc2626}
.wd-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.wd-card{background:#fff;border:1px solid #e0e0e0;padding:16px}.wd-card-head{display:flex;align-items:center;gap:10px;margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid #f0f0f0}.wd-card-head strong{font-size:15px;font-weight:600}.wd-card-body{display:grid;grid-template-columns:1fr 1fr;gap:8px}.wd-stat{text-align:center;padding:8px}.wd-stat span{font-size:11px;color:#999}.wd-stat strong{font-size:20px;font-weight:700}.st-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#bbb}.st-dot.on{background:#059669}
.crud-bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.crud-s{position:relative;flex:1;max-width:300px}.crud-s svg{position:absolute;left:10px;top:50%;transform:translateY(-50%);color:#bbb}.crud-s input{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fff}.crud-bar select{height:36px;padding:0 10px;border:1px solid #e0e0e0;font-size:12px;background:#fff;color:#1a1a1a;outline:none;min-width:80px}.crud-bar select option{color:#1a1a1a;background:#fff}.crud-add{height:36px;padding:0 16px;border:none;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap}.crud-add:hover{background:#333}
.crud-tbl-w{background:#fff;border:1px solid #e0e0e0;overflow:auto}.crud-tbl{width:100%;border-collapse:collapse}.crud-tbl th{text-align:left;padding:10px 14px;font-size:11px;color:#999;font-weight:600;background:#fafafa;border-bottom:1px solid #eee;white-space:nowrap}.crud-tbl td{padding:8px 14px;font-size:13px;border-bottom:1px solid #f5f5f5}.crud-tbl tbody tr:hover{background:#f9f9f9}.th-act,.td-act{width:80px;white-space:nowrap}.crud-empty{text-align:center;color:#ccc;padding:40px!important}
.td-act{display:flex;gap:4px}.ab{width:28px;height:28px;border:1px solid #e0e0e0;background:#fff;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;color:#666}.ab:hover{background:#f5f5f5}.ab.da:hover{background:#fef2f2;border-color:#fecaca;color:#dc2626}
.crud-pager{display:flex;align-items:center;justify-content:space-between}.crud-pager span{font-size:12px;color:#999}.pg-btns{display:flex;gap:4px}.pg-btns button{width:30px;height:30px;border:1px solid #e0e0e0;background:#fff;font-size:12px;cursor:pointer;color:#555}.pg-btns button:hover:not(:disabled){background:#f5f5f5}.pg-btns button.on{background:#1a1a1a;color:#fff;border-color:#1a1a1a}.pg-btns button:disabled{opacity:.3;cursor:default}
.mod-o{position:fixed;inset:0;background:rgba(0,0,0,.2);display:grid;place-items:center;z-index:200}.mod{width:min(520px,calc(100vw-32px));background:#fff;border:1px solid #e0e0e0;box-shadow:0 20px 60px rgba(0,0,0,.1)}.mod-h{display:flex;align-items:center;justify-content:space-between;padding:14px 24px;border-bottom:1px solid #eee}.mod-h h3{margin:0;font-size:16px;font-weight:600}.mod-x{border:none;background:none;font-size:22px;color:#bbb;cursor:pointer}.mod-b{padding:20px 24px;display:grid;gap:14px}.mod-f{display:flex;justify-content:flex-end;gap:10px;padding:14px 24px;border-top:1px solid #eee}.mr2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mf{display:grid;gap:5px}.mf span{font-size:12px;color:#888;font-weight:500}.mf input,.mf select{height:36px;padding:0 12px;border:1px solid #e0e0e0;font-size:13px;outline:none;background:#fafafa;color:#1a1a1a}.mf input:focus,.mf select:focus{border-color:#888;background:#fff}.mf select option{color:#1a1a1a;background:#fff}.mb{height:36px;padding:0 20px;border:none;font-size:13px;font-weight:500;cursor:pointer}.mb.p{background:#1a1a1a;color:#fff}.mb.s{background:#fff;border:1px solid #e0e0e0;color:#555}
</style>
