-- Relax overly strict NOT NULL on QC docs so draft create matches yunshu-ui UX
ALTER TABLE qc_oqc
  MODIFY COLUMN client_id BIGINT UNSIGNED NULL COMMENT '客户ID',
  MODIFY COLUMN client_code VARCHAR(64) NULL COMMENT '客户编码',
  MODIFY COLUMN client_name VARCHAR(255) NULL COMMENT '客户名称',
  MODIFY COLUMN item_id BIGINT UNSIGNED NULL COMMENT '产品物料ID',
  MODIFY COLUMN quantity_out DOUBLE(12,4) NULL DEFAULT 0 COMMENT '发货数量',
  MODIFY COLUMN quantity_check DOUBLE(12,4) NULL DEFAULT 0 COMMENT '本次检测数量';

ALTER TABLE qc_iqc
  MODIFY COLUMN vendor_id BIGINT UNSIGNED NULL COMMENT '供应商ID',
  MODIFY COLUMN vendor_code VARCHAR(64) NULL COMMENT '供应商编码',
  MODIFY COLUMN vendor_name VARCHAR(255) NULL COMMENT '供应商名称',
  MODIFY COLUMN item_id BIGINT UNSIGNED NULL COMMENT '产品物料ID',
  MODIFY COLUMN quantity_recived DOUBLE(12,4) NULL DEFAULT 0 COMMENT '接收数量',
  MODIFY COLUMN quantity_check DOUBLE(12,4) NULL DEFAULT 0 COMMENT '检测数量';

ALTER TABLE qc_ipqc
  MODIFY COLUMN item_id BIGINT UNSIGNED NULL COMMENT '产品物料ID',
  MODIFY COLUMN quantity_check DOUBLE(12,4) NULL DEFAULT 0 COMMENT '检测数量';

ALTER TABLE qc_rqc
  MODIFY COLUMN item_id BIGINT UNSIGNED NULL COMMENT '产品物料ID',
  MODIFY COLUMN quantity_check DOUBLE(12,4) NULL DEFAULT 0 COMMENT '检测数量';
