-- yunshu production feedback + WM consume/produce

CREATE TABLE pro_feedback (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  feedback_type VARCHAR(64) NOT NULL,
  feedback_code VARCHAR(64) NULL,
  workstation_id BIGINT UNSIGNED NOT NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(255) NULL,
  workorder_id BIGINT UNSIGNED NOT NULL,
  workorder_code VARCHAR(64) NULL,
  workorder_name VARCHAR(255) NULL,
  route_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  route_code VARCHAR(64) NULL,
  process_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  task_id BIGINT UNSIGNED NULL,
  task_code VARCHAR(64) NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code VARCHAR(64) NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  unit_of_measure VARCHAR(64) NULL,
  unit_name VARCHAR(64) NULL,
  specification VARCHAR(500) NULL,
  quantity DOUBLE(14,2) NULL,
  quantity_feedback DOUBLE(14,2) NULL,
  quantity_qualified DOUBLE(14,2) NULL,
  quantity_unquanlified DOUBLE(14,2) NULL,
  quantity_uncheck DOUBLE(14,2) NULL,
  user_name VARCHAR(64) NULL,
  nick_name VARCHAR(64) NULL,
  feedback_channel VARCHAR(64) NULL,
  feedback_time DATETIME(3) NULL,
  record_user VARCHAR(64) NULL,
  record_nick VARCHAR(64) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PREPARE',
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (record_id),
  KEY idx_pro_feedback_wo (workorder_id),
  KEY idx_pro_feedback_task (task_id)
) ENGINE=InnoDB COMMENT='生产报工';

CREATE TABLE wm_item_consume (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workorder_id BIGINT UNSIGNED NULL,
  workorder_code VARCHAR(64) NULL,
  workorder_name VARCHAR(255) NULL,
  task_id BIGINT UNSIGNED NULL,
  task_code VARCHAR(64) NULL,
  task_name VARCHAR(255) NULL,
  workstation_id BIGINT UNSIGNED NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(255) NULL,
  process_id BIGINT UNSIGNED NULL,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  feedback_id BIGINT UNSIGNED NULL,
  consume_date DATETIME(3) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PREPARE',
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (record_id)
) ENGINE=InnoDB COMMENT='物料消耗';

CREATE TABLE wm_item_consume_line (
  line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  record_id BIGINT UNSIGNED NULL,
  material_stock_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code VARCHAR(64) NULL,
  item_name VARCHAR(255) NULL,
  specification VARCHAR(500) NULL,
  unit_of_measure VARCHAR(64) NULL,
  unit_name VARCHAR(64) NULL,
  quantity_consume DOUBLE(12,2) NOT NULL,
  batch_id BIGINT UNSIGNED NULL,
  batch_code VARCHAR(255) NULL,
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (line_id),
  KEY idx_wm_item_consume_line_record (record_id)
) ENGINE=InnoDB COMMENT='物料消耗行';

CREATE TABLE wm_item_consume_detail (
  detail_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  line_id BIGINT UNSIGNED NULL,
  record_id BIGINT UNSIGNED NULL,
  material_stock_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code VARCHAR(64) NULL,
  item_name VARCHAR(255) NULL,
  specification VARCHAR(500) NULL,
  unit_of_measure VARCHAR(64) NULL,
  unit_name VARCHAR(64) NULL,
  quantity DOUBLE(12,2) NOT NULL DEFAULT 0,
  batch_id BIGINT UNSIGNED NULL,
  batch_code VARCHAR(255) NULL,
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (detail_id)
) ENGINE=InnoDB COMMENT='物料消耗明细';

CREATE TABLE wm_product_produce (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workorder_id BIGINT UNSIGNED NULL,
  workorder_code VARCHAR(64) NULL,
  workorder_name VARCHAR(255) NULL,
  task_id BIGINT UNSIGNED NULL,
  task_code VARCHAR(64) NULL,
  task_name VARCHAR(255) NULL,
  workstation_id BIGINT UNSIGNED NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(255) NULL,
  process_id BIGINT UNSIGNED NULL,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  feedback_id BIGINT UNSIGNED NULL,
  produce_date DATETIME(3) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PREPARE',
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (record_id)
) ENGINE=InnoDB COMMENT='产品产出';

CREATE TABLE wm_product_produce_line (
  line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  record_id BIGINT UNSIGNED NULL,
  material_stock_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code VARCHAR(64) NULL,
  item_name VARCHAR(255) NULL,
  specification VARCHAR(500) NULL,
  unit_of_measure VARCHAR(64) NULL,
  unit_name VARCHAR(64) NULL,
  quantity_produce DOUBLE(12,2) NOT NULL,
  batch_id BIGINT UNSIGNED NULL,
  batch_code VARCHAR(255) NULL,
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (line_id),
  KEY idx_wm_product_produce_line_record (record_id)
) ENGINE=InnoDB COMMENT='产品产出行';

CREATE TABLE wm_product_produce_detail (
  detail_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  line_id BIGINT UNSIGNED NULL,
  record_id BIGINT UNSIGNED NULL,
  material_stock_id BIGINT UNSIGNED NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code VARCHAR(64) NULL,
  item_name VARCHAR(255) NULL,
  specification VARCHAR(500) NULL,
  unit_of_measure VARCHAR(64) NULL,
  unit_name VARCHAR(64) NULL,
  quantity DOUBLE(12,2) NOT NULL DEFAULT 0,
  batch_id BIGINT UNSIGNED NULL,
  batch_code VARCHAR(255) NULL,
  remark VARCHAR(500) NOT NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NOT NULL DEFAULT 0,
  attr4 INT NOT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME(3) NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME(3) NULL,
  PRIMARY KEY (detail_id)
) ENGINE=InnoDB COMMENT='产品产出明细';
