-- pro_andon_* tables for yunshu-ui Andon center (KTG-compatible API shape)

CREATE TABLE IF NOT EXISTS pro_andon_config (
  config_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  andon_reason VARCHAR(500) NOT NULL COMMENT '呼叫原因',
  andon_level VARCHAR(64) NOT NULL COMMENT '级别',
  handler_role_id BIGINT UNSIGNED NULL,
  handler_role_name VARCHAR(128) NULL,
  handler_user_id BIGINT UNSIGNED NULL,
  handler_user_name VARCHAR(64) NULL,
  handler_nick_name VARCHAR(64) NULL,
  remark VARCHAR(500) NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NULL DEFAULT 0,
  attr4 INT NULL DEFAULT 0,
  create_by VARCHAR(64) NULL DEFAULT '',
  create_time DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_by VARCHAR(64) NULL DEFAULT '',
  update_time DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (config_id)
) ENGINE=InnoDB COMMENT='安灯呼叫配置';

CREATE TABLE IF NOT EXISTS pro_andon_record (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workstation_id BIGINT UNSIGNED NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(128) NULL,
  user_id BIGINT UNSIGNED NULL,
  user_name VARCHAR(64) NULL,
  nick_name VARCHAR(128) NULL,
  workorder_id BIGINT UNSIGNED NULL,
  workorder_code VARCHAR(64) NULL,
  workorder_name VARCHAR(255) NULL,
  process_id BIGINT UNSIGNED NULL,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  andon_reason VARCHAR(500) NOT NULL,
  andon_level VARCHAR(64) NULL DEFAULT 'LEVEL3',
  handle_time DATETIME(3) NULL,
  handler_user_id BIGINT UNSIGNED NULL,
  handler_user_name VARCHAR(64) NULL,
  handler_nick_name VARCHAR(64) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'ACTIVE',
  remark VARCHAR(500) NULL DEFAULT '',
  attr1 VARCHAR(64) NULL COMMENT 'bridged andon_event_id',
  attr2 VARCHAR(255) NULL,
  attr3 INT NULL DEFAULT 0,
  attr4 INT NULL DEFAULT 0,
  create_by VARCHAR(64) NULL DEFAULT '',
  create_time DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_by VARCHAR(64) NULL DEFAULT '',
  update_time DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (record_id),
  KEY idx_pro_andon_record_status (status, create_time),
  KEY idx_pro_andon_record_workstation (workstation_id)
) ENGINE=InnoDB COMMENT='安灯呼叫记录';
