-- dv_* equipment tables for yunshu-ui device center (KTG-compatible API shape)
-- File encoding: UTF-8 (no BOM). All tables use utf8mb4.

SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS dv_machinery_type (
  machinery_type_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '设备类型ID',
  machinery_type_code VARCHAR(64) NOT NULL COMMENT '设备类型编码',
  machinery_type_name VARCHAR(255) NOT NULL COMMENT '设备类型名称',
  parent_type_id BIGINT UNSIGNED NULL DEFAULT 0 COMMENT '父类型ID',
  ancestors VARCHAR(255) NOT NULL COMMENT '所有父节点ID',
  enable_flag CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '是否启用',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (machinery_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备类型表';

CREATE TABLE IF NOT EXISTS dv_machinery (
  machinery_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '设备ID',
  machinery_code VARCHAR(64) NOT NULL COMMENT '设备编码',
  machinery_name VARCHAR(255) NOT NULL COMMENT '设备名称',
  machinery_brand VARCHAR(255) NULL COMMENT '品牌',
  machinery_spec VARCHAR(255) NULL COMMENT '规格型号',
  machinery_type_id BIGINT UNSIGNED NOT NULL COMMENT '设备类型ID',
  machinery_type_code VARCHAR(64) NULL COMMENT '设备类型编码',
  machinery_type_name VARCHAR(255) NULL COMMENT '设备类型名称',
  workshop_id BIGINT UNSIGNED NOT NULL COMMENT '所属车间ID',
  workshop_code VARCHAR(64) NULL COMMENT '所属车间编码',
  workshop_name VARCHAR(255) NULL COMMENT '所属车间名称',
  last_mainten_time DATETIME(3) NULL COMMENT '最近保养时间',
  last_check_time DATETIME(3) NULL COMMENT '最近点检时间',
  status VARCHAR(64) NOT NULL DEFAULT 'STOP' COMMENT '设备状态',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (machinery_id),
  KEY idx_dv_machinery_type (machinery_type_id),
  KEY idx_dv_machinery_workshop (workshop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备表';

CREATE TABLE IF NOT EXISTS dv_subject (
  subject_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  subject_code VARCHAR(64) NOT NULL COMMENT '项目编码',
  subject_name VARCHAR(255) NULL COMMENT '项目名称',
  subject_type VARCHAR(64) NULL DEFAULT '0' COMMENT '项目类型',
  subject_content VARCHAR(500) NOT NULL COMMENT '项目内容',
  subject_standard VARCHAR(255) NULL COMMENT '标准',
  enable_flag CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '是否启用',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备点检保养项目表';

CREATE TABLE IF NOT EXISTS dv_check_plan (
  plan_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '计划ID',
  plan_code VARCHAR(64) NOT NULL COMMENT '计划编码',
  plan_name VARCHAR(255) NULL COMMENT '计划名称',
  plan_type VARCHAR(64) NOT NULL COMMENT '计划类型',
  start_date DATETIME(3) NULL COMMENT '开始日期',
  end_date DATETIME(3) NULL COMMENT '结束日期',
  cycle_type VARCHAR(64) NULL COMMENT '频率',
  cycle_count INT NULL COMMENT '次数',
  status VARCHAR(64) NULL COMMENT '状态',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备点检保养计划头表';

CREATE TABLE IF NOT EXISTS dv_check_machinery (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水号',
  plan_id BIGINT UNSIGNED NOT NULL COMMENT '计划ID',
  machinery_id BIGINT UNSIGNED NOT NULL COMMENT '设备ID',
  machinery_code VARCHAR(64) NOT NULL COMMENT '设备编码',
  machinery_name VARCHAR(255) NOT NULL COMMENT '设备名称',
  machinery_brand VARCHAR(255) NULL COMMENT '品牌',
  machinery_spec VARCHAR(255) NULL COMMENT '规格型号',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (record_id),
  KEY idx_dv_check_machinery_plan (plan_id),
  KEY idx_dv_check_machinery_machinery (machinery_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='点检设备表';

CREATE TABLE IF NOT EXISTS dv_check_subject (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水号',
  plan_id BIGINT UNSIGNED NOT NULL COMMENT '计划ID',
  subject_id BIGINT UNSIGNED NOT NULL COMMENT '项目ID',
  subject_code VARCHAR(64) NOT NULL COMMENT '项目编码',
  subject_name VARCHAR(255) NULL COMMENT '项目名称',
  subject_type VARCHAR(64) NULL COMMENT '项目类型',
  subject_content VARCHAR(500) NOT NULL COMMENT '项目内容',
  subject_standard VARCHAR(255) NULL COMMENT '标准',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (record_id),
  KEY idx_dv_check_subject_plan (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='点检项目表';

CREATE TABLE IF NOT EXISTS dv_check_record (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  plan_id BIGINT UNSIGNED NULL COMMENT '计划ID',
  plan_code VARCHAR(64) NULL COMMENT '计划编码',
  plan_name VARCHAR(255) NULL COMMENT '计划名称',
  plan_type VARCHAR(64) NULL COMMENT '计划类型',
  machinery_id BIGINT UNSIGNED NOT NULL COMMENT '设备ID',
  machinery_code VARCHAR(64) NOT NULL COMMENT '设备编码',
  machinery_name VARCHAR(255) NOT NULL COMMENT '设备名称',
  machinery_brand VARCHAR(255) NULL COMMENT '品牌',
  machinery_spec VARCHAR(255) NULL COMMENT '规格型号',
  check_time DATETIME(3) NOT NULL COMMENT '点检时间',
  user_id BIGINT UNSIGNED NULL COMMENT '点检人',
  user_name VARCHAR(64) NULL COMMENT '点检人用户名',
  nick_name VARCHAR(255) NULL COMMENT '点检人名称',
  status VARCHAR(64) NULL DEFAULT 'PREPARE' COMMENT '状态',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (record_id),
  KEY idx_dv_check_record_machinery (machinery_id),
  KEY idx_dv_check_record_plan (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备点检记录表';

CREATE TABLE IF NOT EXISTS dv_check_record_line (
  line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '行ID',
  record_id BIGINT UNSIGNED NOT NULL COMMENT '记录ID',
  subject_id BIGINT UNSIGNED NOT NULL COMMENT '项目ID',
  subject_code VARCHAR(64) NOT NULL COMMENT '项目编码',
  subject_name VARCHAR(255) NULL COMMENT '项目名称',
  subject_type VARCHAR(64) NULL COMMENT '项目类型',
  subject_content VARCHAR(500) NOT NULL COMMENT '项目内容',
  subject_standard VARCHAR(255) NULL COMMENT '标准',
  check_status VARCHAR(64) NOT NULL COMMENT '点检结果',
  check_result VARCHAR(500) NULL COMMENT '异常描述',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (line_id),
  KEY idx_dv_check_record_line_record (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备点检记录行表';

CREATE TABLE IF NOT EXISTS dv_mainten_record (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  plan_id BIGINT UNSIGNED NULL COMMENT '计划ID',
  plan_code VARCHAR(64) NULL COMMENT '计划编码',
  plan_name VARCHAR(255) NULL COMMENT '计划名称',
  plan_type VARCHAR(64) NULL COMMENT '计划类型',
  machinery_id BIGINT UNSIGNED NOT NULL COMMENT '设备ID',
  machinery_code VARCHAR(64) NOT NULL COMMENT '设备编码',
  machinery_name VARCHAR(255) NOT NULL COMMENT '设备名称',
  machinery_brand VARCHAR(255) NULL COMMENT '品牌',
  machinery_spec VARCHAR(255) NULL COMMENT '规格型号',
  mainten_time DATETIME(3) NOT NULL COMMENT '保养时间',
  user_id BIGINT UNSIGNED NULL COMMENT '用户ID',
  user_name VARCHAR(64) NULL COMMENT '用户名',
  nick_name VARCHAR(128) NULL COMMENT '昵称',
  status VARCHAR(64) NULL DEFAULT 'PREPARE' COMMENT '状态',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (record_id),
  KEY idx_dv_mainten_record_machinery (machinery_id),
  KEY idx_dv_mainten_record_plan (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备保养记录表';

CREATE TABLE IF NOT EXISTS dv_mainten_record_line (
  line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '行ID',
  record_id BIGINT UNSIGNED NOT NULL COMMENT '记录ID',
  subject_id BIGINT UNSIGNED NOT NULL COMMENT '项目ID',
  subject_code VARCHAR(64) NOT NULL COMMENT '项目编码',
  subject_name VARCHAR(255) NULL COMMENT '项目名称',
  subject_type VARCHAR(64) NULL COMMENT '项目类型',
  subject_content VARCHAR(500) NOT NULL COMMENT '项目内容',
  subject_standard VARCHAR(255) NULL COMMENT '标准',
  mainten_status VARCHAR(64) NOT NULL COMMENT '保养结果',
  mainten_result VARCHAR(500) NULL COMMENT '异常描述',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (line_id),
  KEY idx_dv_mainten_record_line_record (record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备保养记录行表';

CREATE TABLE IF NOT EXISTS dv_repair (
  repair_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '维修单ID',
  repair_code VARCHAR(64) NOT NULL COMMENT '维修单编号',
  repair_name VARCHAR(255) NULL COMMENT '维修单名称',
  machinery_id BIGINT UNSIGNED NOT NULL COMMENT '设备ID',
  machinery_code VARCHAR(64) NOT NULL COMMENT '设备编码',
  machinery_name VARCHAR(255) NOT NULL COMMENT '设备名称',
  machinery_brand VARCHAR(255) NULL COMMENT '品牌',
  machinery_spec VARCHAR(255) NULL COMMENT '规格型号',
  machinery_type_id BIGINT UNSIGNED NULL COMMENT '设备类型ID',
  require_date DATETIME(3) NULL COMMENT '报修日期',
  finish_date DATETIME(3) NULL COMMENT '维修完成日期',
  confirm_date DATETIME(3) NULL COMMENT '验收日期',
  repair_result VARCHAR(64) NULL COMMENT '维修结果',
  accepted_id BIGINT UNSIGNED NULL COMMENT '维修人员ID',
  accepted_name VARCHAR(64) NULL COMMENT '维修人员用户名',
  accepted_by VARCHAR(64) NULL COMMENT '维修人员名称',
  confirm_id BIGINT UNSIGNED NULL COMMENT '验收人员ID',
  confirm_name VARCHAR(64) NULL COMMENT '验收人员用户名',
  confirm_by VARCHAR(64) NULL COMMENT '验收人员名称',
  source_doc_type VARCHAR(64) NULL COMMENT '来源单据类型',
  source_doc_id BIGINT UNSIGNED NULL COMMENT '来源单据ID',
  source_doc_code VARCHAR(64) NULL COMMENT '来源单据编号',
  status VARCHAR(64) NULL DEFAULT 'PREPARE' COMMENT '单据状态',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (repair_id),
  KEY idx_dv_repair_machinery (machinery_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备维修单';

CREATE TABLE IF NOT EXISTS dv_repair_line (
  line_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '行ID',
  repair_id BIGINT UNSIGNED NOT NULL COMMENT '维修单ID',
  subject_id BIGINT UNSIGNED NULL COMMENT '项目ID',
  subject_code VARCHAR(64) NULL COMMENT '项目编码',
  subject_name VARCHAR(255) NULL COMMENT '项目名称',
  subject_type VARCHAR(64) NULL COMMENT '项目类型',
  subject_content VARCHAR(500) NULL COMMENT '项目内容',
  subject_standard VARCHAR(255) NULL COMMENT '标准',
  malfunction VARCHAR(500) NOT NULL COMMENT '故障描述',
  malfunction_url VARCHAR(255) NULL COMMENT '故障描述资源',
  repair_des VARCHAR(500) NULL COMMENT '维修情况',
  remark VARCHAR(500) NULL DEFAULT '' COMMENT '备注',
  attr1 VARCHAR(64) NULL COMMENT '预留字段1',
  attr2 VARCHAR(255) NULL COMMENT '预留字段2',
  attr3 INT NULL DEFAULT 0 COMMENT '预留字段3',
  attr4 INT NULL DEFAULT 0 COMMENT '预留字段4',
  create_by VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  create_time DATETIME(3) NULL COMMENT '创建时间',
  update_by VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  update_time DATETIME(3) NULL COMMENT '更新时间',
  PRIMARY KEY (line_id),
  KEY idx_dv_repair_line_repair (repair_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备维修单行';
