-- V23: 分析集成 — UReport / 图形报表 / 流转卡 / 打印管理
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS ureport_file_tbl (
  id_ INT NOT NULL AUTO_INCREMENT,
  name_ VARCHAR(100) NOT NULL,
  content_ MEDIUMBLOB NULL,
  create_time_ TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  update_time_ TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id_),
  UNIQUE KEY uk_ureport_name (name_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='UReport 报表文件';

CREATE TABLE IF NOT EXISTS report_chart (
  chart_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  chart_code VARCHAR(64) NOT NULL,
  chart_name VARCHAR(128) NOT NULL,
  chart_type VARCHAR(64) NULL,
  business_type VARCHAR(64) NULL,
  api VARCHAR(500) NULL,
  options TEXT NULL,
  chart_pic VARCHAR(500) NULL,
  enable_flag CHAR(1) NOT NULL DEFAULT 'Y',
  remark VARCHAR(500) NULL,
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 BIGINT NULL,
  attr4 BIGINT NULL,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (chart_id),
  UNIQUE KEY uk_report_chart_code (chart_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图形报表';

CREATE TABLE IF NOT EXISTS report_chart_role (
  chart_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (chart_id, role_id),
  KEY idx_report_chart_role_role (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图形报表角色';

CREATE TABLE IF NOT EXISTS pro_card (
  card_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  card_code VARCHAR(64) NOT NULL,
  workorder_id BIGINT UNSIGNED NULL,
  workorder_code VARCHAR(64) NULL,
  workorder_name VARCHAR(255) NULL,
  batch_code VARCHAR(64) NULL,
  item_id BIGINT UNSIGNED NULL,
  item_code VARCHAR(64) NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  specification VARCHAR(500) NULL,
  unit_of_measure VARCHAR(64) NOT NULL DEFAULT 'PCS',
  barcode_url VARCHAR(255) NULL,
  quantity_transfered DOUBLE(12,2) NULL,
  status VARCHAR(64) NULL,
  remark VARCHAR(500) NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NULL DEFAULT 0,
  attr4 INT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (card_id),
  UNIQUE KEY uk_pro_card_code (card_code),
  KEY idx_pro_card_workorder (workorder_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工序流转卡';

CREATE TABLE IF NOT EXISTS pro_card_process (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  card_id BIGINT UNSIGNED NOT NULL,
  card_code VARCHAR(64) NULL,
  seq_num INT NOT NULL DEFAULT 1,
  process_id BIGINT UNSIGNED NULL,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  input_time DATETIME NULL,
  output_time DATETIME NULL,
  quantity_input DOUBLE(12,2) NULL,
  quantity_output DOUBLE(12,2) NULL,
  quantity_unquanlify DOUBLE(12,2) NULL,
  workstation_id BIGINT UNSIGNED NOT NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(125) NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  user_name VARCHAR(64) NULL,
  nick_name VARCHAR(125) NULL,
  ipqc_id BIGINT UNSIGNED NULL,
  remark VARCHAR(500) NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NULL DEFAULT 0,
  attr4 INT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (record_id),
  KEY idx_pro_card_process_card (card_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流转卡工序';

CREATE TABLE IF NOT EXISTS pro_sn_process (
  record_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sn_id BIGINT UNSIGNED NOT NULL,
  sn_code VARCHAR(64) NULL,
  seq_num INT NOT NULL DEFAULT 1,
  process_id BIGINT UNSIGNED NULL,
  process_code VARCHAR(64) NULL,
  process_name VARCHAR(255) NULL,
  input_time DATETIME NULL,
  output_time DATETIME NULL,
  quantity_input DOUBLE(12,2) NULL,
  quantity_output DOUBLE(12,2) NULL,
  quantity_unquanlify DOUBLE(12,2) NULL,
  workstation_id BIGINT UNSIGNED NOT NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(125) NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  user_name VARCHAR(64) NULL,
  nick_name VARCHAR(125) NULL,
  ipqc_id BIGINT UNSIGNED NULL,
  remark VARCHAR(500) NULL DEFAULT '',
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 INT NULL DEFAULT 0,
  attr4 INT NULL DEFAULT 0,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (record_id),
  KEY idx_pro_sn_process_sn (sn_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SN工序流转';

CREATE TABLE IF NOT EXISTS print_template (
  template_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_code VARCHAR(64) NOT NULL,
  template_name VARCHAR(128) NOT NULL,
  template_type VARCHAR(64) NULL,
  template_json LONGTEXT NULL,
  paper_type VARCHAR(32) NULL,
  template_width INT NULL,
  template_height INT NULL,
  is_default CHAR(1) NOT NULL DEFAULT 'N',
  enable_flag CHAR(1) NOT NULL DEFAULT 'Y',
  remark VARCHAR(500) NULL,
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 BIGINT NULL,
  attr4 BIGINT NULL,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  template_pic VARCHAR(500) NULL,
  PRIMARY KEY (template_id),
  UNIQUE KEY uk_print_template_code (template_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='打印模板';

CREATE TABLE IF NOT EXISTS print_client (
  client_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_code VARCHAR(64) NOT NULL,
  client_name VARCHAR(128) NOT NULL,
  client_ip VARCHAR(64) NULL,
  client_port BIGINT NULL,
  client_token VARCHAR(128) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
  workshop_id BIGINT UNSIGNED NULL,
  workshop_code VARCHAR(64) NULL,
  workshop_name VARCHAR(128) NULL,
  workstation_id BIGINT UNSIGNED NULL,
  workstation_code VARCHAR(64) NULL,
  workstation_name VARCHAR(128) NULL,
  remark VARCHAR(500) NULL,
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 BIGINT NULL,
  attr4 BIGINT NULL,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (client_id),
  UNIQUE KEY uk_print_client_code (client_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='打印客户端';

CREATE TABLE IF NOT EXISTS print_printer_config (
  printer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id BIGINT UNSIGNED NULL,
  printer_code VARCHAR(64) NULL,
  printer_type VARCHAR(64) NULL,
  printer_name VARCHAR(128) NOT NULL,
  brand VARCHAR(64) NULL,
  printer_model VARCHAR(128) NULL,
  connection_type VARCHAR(32) NULL,
  printer_url VARCHAR(500) NULL,
  printer_ip VARCHAR(64) NULL,
  printer_port BIGINT NULL,
  enable_flag CHAR(1) NOT NULL DEFAULT 'Y',
  status VARCHAR(32) NULL,
  default_flag CHAR(1) NOT NULL DEFAULT 'N',
  remark VARCHAR(500) NULL,
  attr1 VARCHAR(64) NULL,
  attr2 VARCHAR(255) NULL,
  attr3 BIGINT NULL,
  attr4 BIGINT NULL,
  create_by VARCHAR(64) NOT NULL DEFAULT '',
  create_time DATETIME NULL,
  update_by VARCHAR(64) NOT NULL DEFAULT '',
  update_time DATETIME NULL,
  PRIMARY KEY (printer_id),
  KEY idx_print_printer_client (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='打印机配置';
